# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
# This file is generated from the source file pathfinding.proto. If you edit this file, you will likely lose your changes.
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

try:
    from . import pathfinding_pb2 as pathfinding__pb2
except Exception:  # pragma: no cover - fallback for direct import
    import pathfinding_pb2 as pathfinding__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in pathfinding_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RouteSearchStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFastestPath = channel.unary_unary(
                '/pathfinding.RouteSearch/GetFastestPath',
                request_serializer=pathfinding__pb2.PathRequest.SerializeToString,
                response_deserializer=pathfinding__pb2.PathResponse.FromString,
                _registered_method=True)


class RouteSearchServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetFastestPath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RouteSearchServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFastestPath': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFastestPath,
                    request_deserializer=pathfinding__pb2.PathRequest.FromString,
                    response_serializer=pathfinding__pb2.PathResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pathfinding.RouteSearch', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pathfinding.RouteSearch', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RouteSearch(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetFastestPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pathfinding.RouteSearch/GetFastestPath',
            pathfinding__pb2.PathRequest.SerializeToString,
            pathfinding__pb2.PathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
